### ISSUE TITLE
Can't init project

### ISSUE THREAD

**Issue by nukadelic** [ErkrodC/UnityChess#12]
Cloned it on my local machine but the `Game` class seems to be different.  
```
HalfMoveTimeline
LatestHalfMoveIndex
TryExecuteMove
...
```
Also the master branch seems to be missing ( 404 )

**Comment by ErkrodC** [comment]
'master' is reserved for releases. Since there have been no releases yet, 'development' represents the most up-to-date version of the project.
The latest 'development' (and sub branches) will already be associated with a submodule commit hash, which will be the latest commit on the submodule branch that you need to have checked out (e.g. for UnityChess-development it'll be the latest on UnityChessLib-development).

Also keep in mind UnityChess-master branch is currently behind the commit that initialized the UnityChessLib submodule, so try to stay off that branch for now as it may mess with your local repo settings.

**Comment by nukadelic** [comment]
Thank you for the help it works now.  

just gonna drop this here, in case anyone else is facing the same issue, this is what i used inside the UnityChessLib folder
```
C:\Github\UnityChess\Assets\Scripts\UnityChessLib>
git clone --single-branch --branch development https://github.com/ErkrodC/UnityChessLib.git .
```

**Comment by ErkrodC** [comment]
I created a new [wiki page](https://github.com/ErkrodC/UnityChess/wiki/Getting-The-Project) to hopefully clarify the project a bit.

**Comment by nukadelic** [comment]
@ErkrodC wow that's very detailed page. Could you make a quick overview of the ChessLib ? I'm in a middle of deconstructing the main project to able to understand the Lib better and implement into my own project. If you would happened to have some spare time, please add me via discord `Wad1m#6844` I would like to learn more about your project. Cheers.

**Comment by ErkrodC** [comment]
Ask and you shall [receive](https://github.com/ErkrodC/UnityChess/wiki/The-UnityChessLib-Submodule). Still a WIP, but hopefully it will get you started.
